### ISSUE TITLE
Fasta file not found

### ISSUE THREAD

**Issue by cdlawless** [compomics/peptide-shaker#129]
I have been using the following command with SearchGUI (v2.6.1):

java -Xms4096M -Xmx131072M -cp /mnt/fls01-home01/mjfidcl2/scratch/SearchGUI/SearchGUI-2.6.1/SearchGUI-2.6.1.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files "/mnt/lustre/scratch/mjfidcl2/DDIP/Fraction
35/Qex/mgfs/" -output_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/ -id_params /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/F35_Qex_Vanilla.par -output_option 0 -output_data 1 -mgf_splitti
ng 2000 -temp_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp -xtandem 1 -msgf 1 -omssa 1 -myrimatch 1 -comet 1 -tide 0 -ms_amanda 0 -andromeda 0 -xtandem_folder /mnt/lustre/scratch/mjfidcl2
/DDIP/Fraction35/Qex/temp -myrimatch_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp -comet_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp -omssa_folder /mnt/lustre/scratch/mjf
idcl2/DDIP/Fraction35/Qex/temp -msgf_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp

I then use the zipped output and use with PeptideShaker (v1.7.1):

java -Xms1024m -Xmx262144m -cp /scratch/mjfidcl2/PeptideShaker-1.7.1/PeptideShaker-1.7.1.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment F35_Qex_Vanilla -sample F35_Qex_Vanilla_sample -replica
te 1 -identification_files "/scratch/mjfidcl2/DDIP/Fraction35/Qex/searchgui_out.zip" -out "./F35_Qex_Vanilla.cpsx" -ptm_score 1 -out_reports "./" -reports "0,3,5,7,8" -zip "./F35_Qex_Vanilla.zip" -temp_f
older "/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp/"

I keep getting an error when trying to import the fasta file:
File /mnt/fls01-home01/mjfidcl2/scratch/DDIP/Vanilla/slola_proteome_vanilla_v1_concatenated_target_decoy.fasta was not found. Please select a different FASTA file.

Error:
java.io.FileNotFoundException: The FASTA file '/mnt/fls01-home01/mjfidcl2/scratch/DDIP/Vanilla/slola_proteome_vanilla_v1_concatenated_target_decoy.fasta' could not be found!
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.loadFastaFile(SequenceFactory.java:553)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:175)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:449)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:684)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:203)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:896)

It keeps looking for the fasta file in the location defined in the original .par file even though it is present in the zip file.

Thanks

Craig

**Comment by hbarsnes** [comment]
Hi Craig,

Thanks for telling us about this. This is a bug that we already fixed in the GUI but seems like we forgot to do the same for the command line. We'll get it fixed and will release a new version as soon as possible.

Best regards,
Harald

**Comment by cdlawless** [comment]
Thanks Harald

**Comment by hbarsnes** [comment]
Hi again,

Here's a beta version that ought to fix the problem: https://www.dropbox.com/s/rc60yvk9o4kbwrx/PeptideShaker-1.7.2-beta.zip?dl=0

Let me know if it works for you and then I'll release a proper new version.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Craig,

The issue should be fixed in PeptideShaker v1.7.2. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by cdlawless** [comment]
Hi Harald

Apologies, I have been seconded to another part of our project and have only picked this up again now. I tried with the 1.7.2 beta version and the latest 1.7.4 release and I have still getting the same issue. 

File /mnt/fls01-home01/mjfidcl2/scratch/DDIP/Vanilla/slola_proteome_vanilla_v1_concatenated_target_decoy.fasta was not found. Please select a different FASTA file.
java.io.FileNotFoundException: The FASTA file '/mnt/fls01-home01/mjfidcl2/scratch/DDIP/Vanilla/slola_proteome_vanilla_v1_concatenated_target_decoy.fasta' could not be found!
	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.loadFastaFile(SequenceFactory.java:553)
	at eu.isas.peptideshaker.fileimport.FileImporter.importSequences(FileImporter.java:175)
	at eu.isas.peptideshaker.fileimport.FileImporter$IdProcessorFromFile.importFiles(FileImporter.java:449)
	at eu.isas.peptideshaker.fileimport.FileImporter.importFiles(FileImporter.java:158)
	at eu.isas.peptideshaker.PeptideShaker.importFiles(PeptideShaker.java:232)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.createProject(PeptideShakerCLI.java:693)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.call(PeptideShakerCLI.java:204)
	at eu.isas.peptideshaker.cmd.PeptideShakerCLI.main(PeptideShakerCLI.java:905)

I have also tried using the latest version of SearchGUI (2.6.5) with the above and still get the same issue.

SearchGUI command:
java -Xms4096M -Xmx131072M -cp /mnt/fls01-home01/mjfidcl2/scratch/SearchGUI/SearchGUI-2.6.5/SearchGUI-2.6.5.jar eu.isas.searchgui.cmd.SearchCLI -spectrum_files "/mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/mgfs_1/" -output_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/ -id_params /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/F35_Qex_Vanilla.par -output_option 0 -output_data 1 -mgf_splitting 2000 -temp_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp -xtandem 1 -msgf 1 -omssa 1 -myrimatch 1 -comet 1 -tide 0 -ms_amanda 0 -andromeda 0 -xtandem_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp -myrimatch_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp -comet_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp -omssa_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp -msgf_folder /mnt/lustre/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp 



PeptideShaker command:
java -Xms1024m -Xmx262144m -cp /scratch/mjfidcl2/PeptideShaker-1.7.2-beta/PeptideShaker-1.7.2-beta.jar eu.isas.peptideshaker.cmd.PeptideShakerCLI -experiment F35_Qex_Vanilla -sample F35_Qex_Vanilla_sample -replicate 1 -identification_files "/scratch/mjfidcl2/DDIP/Fraction35/Qex/searchgui_out.zip" -out "./F35_Qex_Vanilla.cpsx" -ptm_score 1 -out_reports "./" -reports "0,3,5,7,8" -zip "./F35_Qex_Vanilla.zip" -temp_folder "/scratch/mjfidcl2/DDIP/Fraction35/Qex/temp/"

**Comment by hbarsnes** [comment]
Hi Craig,

I see now that my fix had a single line that was incorrect and thus the fix had no impact... I'll blame it on trying to fix too many bugs at once. ;)

Just released PeptideShaker v1.7.6. This time with the fix actually working. I hope. :)

Best regards,
Harald
