### ISSUE TITLE
Custom modifications and SearchCLI and PeptideShakerCLI 

### ISSUE THREAD

**Issue by jflucier** [compomics/peptide-shaker#354]
Hello,

I am trying to load new PTM on centos7 cluster as discussed in this thread but cant seem to get this done right. I looked at solution in #299 but cant sem to get this working. Here is the context:

`
# copy fresh install on compute node
cp -r /nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/programs/SearchGUI-3.3.13/ $TEMPDIR/softwares/
cp -r /nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/programs/PeptideShaker-1.16.38/ $TEMPDIR/softwares/
cp /nfs3_ib/ip32/home/xroucou_group/apps/compomics/clean_install/ptmFactory-4.12.14.json $TEMPDIR/mods/

#point to jar file
SEARCHGUI_JAR_PATH=$TEMPDIR/softwares/SearchGUI-3.3.13/SearchGUI-3.3.13.jar
SHAKER_JAR_PATH=$TEMPDIR/softwares/PeptideShaker-1.16.38/PeptideShaker-1.16.38.jar
PWIZ_PATH=/nfs3_ib/ip32/home/xroucou_group/apps_centos7/pwiz_release-3_0_8789

# build db
java -cp $SEARCHGUI_JAR_PATH eu.isas.searchgui.cmd.FastaCLI \
-in $TEMPDIR/db/searchgui_db.fasta -decoy > $OUTPUT_DIR/logs/FastaCLI.log 2>&1

#mxxml to mgf
$PWIZ_PATH/msconvert \
$__IN_DATASET \
--mgf --outdir $TEMPDIR/ --outfile "${__IN_DATASET_NAME}.mgf"

#set ptm path
java -cp $SHAKER_JAR_PATH eu.isas.peptideshaker.cmd.PathSettingsCLI \
-ptm_configuration $TEMPDIR/mods/

# create parameter file
java -cp $SHAKER_JAR_PATH eu.isas.peptideshaker.cmd.IdentificationParametersCLI \
-ms_low_mem_mode $__MS_LOW_MEM_MODE \
-max_charge $__MAX_CHARGE \
-xtandem_min_frag_mz $__XTANDEM_MIN_FRAG_MZ \
-msgf_num_ptms $__MSGF_NUM_PTMS \
-myrimatch_num_ptms $__MYRIMATCH_NUM_PTMS \
-ms_amanda_instrument "'$__MS_AMANDA_INSTRUMENT'" \
-comet_num_ptms $__COMET_NUM_PTMS \
-comet_remove_meth $__COMET_REMOVE_METH \
-tide_num_ptms $__TIDE_NUM_PTMS \
-tide_use_neutral_losses $__TIDE_USE_NEUTRAL_LOSSES \
-db $TEMPDIR/db/searchgui_db_concatenated_target_decoy.fasta \
-out $TEMPDIR/searchgui.parameters \
-enzyme "$__ENZYME_LIST" \
-fixed_mods '"'"$__FIXED_MODS"'"'  \
-variable_mods '"'"$__VARIABLE_MODS"'"' \
-frag_tol $__FRAG_TOL \
-frag_ppm $__FRAG_PPM \
-prec_tol $__PREC_TOL \
-prec_ppm $__PREC_PPM \
-protein_fdr 0.001 \
-msgf_instrument $__MSGF_INSTRUMENT

`

The variable $__VARIABLE_MODS is set to Biotinylation of K, Biotinylation of N-termini.

When I execute IdentificationParametersCLI it returns an error the modification doesnt exist. However in path.txt file, the ptm_configuration path is set well. Also if I grep json file I find the modification:

`
[jflucier@ip15-mp2 QE_0817_10973]$ head -n 100 /nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/temp//temp_ms/QE_0817_10973/softwares/PeptideShaker-1.16.38/resources/conf/paths.txt 
peptideshaker_matches_directory=resources
peptideshaker_user_preferences=/home/jflucier/.peptideshaker
peptideshaker_exports=/home/jflucier/.peptideshaker
unzip=default
utilities_user_preferences=/home/jflucier/.compomics
ptm_configuration=/nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/temp//temp_ms/QE_0817_10973/mods/
enzyme_configuration=default
fasta_indexes=/home/jflucier/.compomics/proteins/indexes/
gene_mapping=/home/jflucier/.compomics/gene_mappings
pride_annotation=/home/jflucier/.compomics/pride/
identification_parameters=/home/jflucier/.compomics

[jflucier@ip15-mp2 QE_0817_10973]$ grep -e 'Biotinylation of K' /nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/temp//temp_ms/QE_0817_10973/mods/ptmFactory-4.12.14.json 
    "Biotinylation of K": {
      "name": "Biotinylation of K",
    "Biotinylation of K",
`

Here is the identificationcli output:

`
[jflucier@ip15-mp2 QE_0817_10973]$ java -cp $SHAKER_JAR_PATH eu.isas.peptideshaker.cmd.IdentificationParametersCLI \
> -ms_low_mem_mode $__MS_LOW_MEM_MODE \
> -max_charge $__MAX_CHARGE \
> -xtandem_min_frag_mz $__XTANDEM_MIN_FRAG_MZ \
> -msgf_num_ptms $__MSGF_NUM_PTMS \
> -myrimatch_num_ptms $__MYRIMATCH_NUM_PTMS \
> -ms_amanda_instrument "'$__MS_AMANDA_INSTRUMENT'" \
> -comet_num_ptms $__COMET_NUM_PTMS \
> -comet_remove_meth $__COMET_REMOVE_METH \
> -tide_num_ptms $__TIDE_NUM_PTMS \
> -tide_use_neutral_losses $__TIDE_USE_NEUTRAL_LOSSES \
> -db $TEMPDIR/db/searchgui_db_concatenated_target_decoy.fasta \
> -out $TEMPDIR/searchgui.parameters \
> -enzyme "$__ENZYME_LIST" \
> -fixed_mods '"'"$__FIXED_MODS"'"'  \
> -variable_mods '"'"$__VARIABLE_MODS"'"' \
> -frag_tol $__FRAG_TOL \
> -frag_ppm $__FRAG_PPM \
> -prec_tol $__PREC_TOL \
> -prec_ppm $__PREC_PPM \
> -protein_fdr 0.001 \
> -msgf_instrument $__MSGF_INSTRUMENT

An error occurred while parsing the variable modifications:
PTM Biotinylation of K not found.

========================
Available Modifications:
========================

........

`
Thanks in asdvance for your help
JF

**Comment by hbarsnes** [comment]
Hi JF,

I need to dig into this a bit more, but it may seem like the path parameters (including the ptm path) is not set when using IdentificationParametersCLI, unlike when running the other command lines.

Try running `eu.isas.peptideshaker.cmd.IdentificationParametersCLI -mods`. That should let you know whether the modifications in question are found or not.

And could you try making the parameter file on the machine where the PTMs were created and then use it on the cluster? You can then use the "-db" option to update the path to the FASTA file if required when running SearchCLI or PeptideShakerCLI.

Best regards,
Harald

**Comment by jflucier** [comment]
Hi Harald, 

thanks for response.

when i run the --mods, modification are not present in list. So the ptmFactory-4.12.14.json is not being loaded

In our current setup, not only the db changes dynamically, but also other options like frag_tol and prec_tol based on MS instrument used. Since we analyse many files from the proteomexchange repo, MS instrument vary based on study. Ideally parameter file should be generated on compute node along with the other steps.

The ptmFactory-4.12.14.json was generated using UI on a windows machine in the lab. The cluster doesnt have access to this window machine.

**Comment by hbarsnes** [comment]
Hi JF,

> when i run the --mods, modification are not present in list. So the ptmFactory-4.12.14.json is not being loaded

Ok, so that confirms my suspicion that the path settings are not being updated before running the IdentificationParametersCLI command line. Which was also what I got from my quick look at the code.

> Ideally parameter file should be generated on compute node along with the other steps.

Yes, I agree. The suggestion to make it on the Windows machine was only to test whether the issue was limited to the IdentificationParametersCLI command line (which I think it should be).

> The ptmFactory-4.12.14.json was generated using UI on a windows machine in the lab. The cluster doesnt have access to this window machine.

Hence my suggestion to add the "-db" option to the SearchCLI and PeptideShakerCLI command lines. :)

In any case, I'll try to get the time to fix the problem and release a new version as soon as possible. Hopefully tomorrow or at the start of next week.

Best regards,
Harald

**Comment by jflucier** [comment]
ok please tell me when release is available. I will try it right away.

thanks so much for your precious help and support

JF

**Comment by hbarsnes** [comment]
Hi JF,

I've now uploaded beta versions of both SearchGUI and PeptideShaker that should solve the problem. Would be great if you could test before I release them properly?

You'll find them here:
- https://www.dropbox.com/s/75qsxf0udvborp5/PeptideShaker-1.16.39-beta.zip?dl=0
- https://www.dropbox.com/s/i4gw2r078iltzc1/SearchGUI-3.3.14-beta-mac_and_linux.tar.gz?dl=0
- https://www.dropbox.com/s/p2inkamyvtb0vi8/SearchGUI-3.3.14-beta-windows.zip?dl=0

Best regards,
Harald

**Comment by jflucier** [comment]
Hi Harald,

`
[jflucier@ip32 db]$ module add java/1.7.0_80
[jflucier@ip32 db]$ java -cp $SHAKER_JAR_PATH eu.isas.peptideshaker.cmd.PathSettingsCLI \
> -ptm_configuration $TEMPDIR/mods/
Error: Could not find or load main class eu.isas.peptideshaker.cmd.PathSettingsCLI
[jflucier@ip32 db]$ java -cp /nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/temp/temp_ms/QE_0817_10973/softwaresPeptideShaker-1.16.39-beta/PeptideShaker-1.16.39-beta.jar eu.isas.peptideshaker.cmd.PathSettingsCLI
Error: Could not find or load main class eu.isas.peptideshaker.cmd.PathSettingsCLI

`

I looked inside peptideshaker jar (see image) and class is there.
[https://drive.google.com/file/d/1YkFgQvjzKySzqhvl9klkiocRul4_HsaP/view?usp=sharing](url)

thanks again for your help
JF

**Comment by hbarsnes** [comment]
Hi JF,

That's strange. The same command line works fine on my side. Your PeptideShaker path looks odd though? Seems to be missing a path separator in between software and PeptideShaker (softwaresPeptideShaker-1.16.39-beta)?

Best regards,
Harald

**Comment by jflucier** [comment]
my gosh... my 2 eyes were closed when looking at this. 

Sorry could not see this misstake.

I ran the following with new peptideshaker version but still cannot get the ptm json file to be loaded properly:

`
[jflucier@ip32 QE_0817_10973]$ grep -e Biotinylation /nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/temp/temp_ms/QE_0817_10973/mods/ptmFactory-4.12.14.json 
    "Biotinylation of K": {
      "name": "Biotinylation of K",
    "Biotinylation of N-termini": {
      "name": "Biotinylation of N-termini",
    "Biotinylation of K",
    "Biotinylation of N-termini",

[jflucier@ip32 QE_0817_10973]$ java -cp $SHAKER_JAR_PATH eu.isas.peptideshaker.cmd.PathSettingsCLI -ptm_configuration /nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/temp/temp_ms/QE_0817_10973/mods/
Path configuration completed.

[jflucier@ip32 QE_0817_10973]$ head -n 1000  softwares/PeptideShaker-1.16.39-beta/resources/conf/paths.txt 
peptideshaker_matches_directory=resources
peptideshaker_user_preferences=/home/jflucier/.peptideshaker
peptideshaker_exports=/home/jflucier/.peptideshaker
unzip=default
utilities_user_preferences=/home/jflucier/.compomics
ptm_configuration=/nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/temp/temp_ms/QE_0817_10973/mods/
enzyme_configuration=default
fasta_indexes=/home/jflucier/.compomics/proteins/indexes/
gene_mapping=/home/jflucier/.compomics/gene_mappings
pride_annotation=/home/jflucier/.compomics/pride/
identification_parameters=/home/jflucier/.compomics

[jflucier@ip32 QE_0817_10973]$ java -cp $SEARCHGUI_JAR_PATH eu.isas.searchgui.cmd.IdentificationParametersCLI --mods | grep -e Biotinylation
[jflucier@ip32 QE_0817_10973]$

[jflucier@ip32 QE_0817_10973]$ echo $SHAKER_JAR_PATH 
/nfs3_ib/ip32/home/xroucou_group/analysis/test/pej_newmodif/temp/temp_ms/QE_0817_10973/softwares/PeptideShaker-1.16.39-beta/PeptideShaker-1.16.39-beta.jar
[jflucier@ip32 QE_0817_10973]$

`

As you can see no Biotinylation mods are detected even if mu mods path is ok in path.txt file

Thanks again so much for your help.
JF

**Comment by hbarsnes** [comment]
Hi JF,

I think the problem is that you are mixing PeptideShakerCLI and SearchCLI command lines. As changing the ptm_configuration path for PeptideShaker does not change it for SearchGUI, and the other way around. So you need to set the path separately for both, or include the -ptm_configuration option directly in the SearchCLI and PeptideShakerCLI command lines. (The perhaps more general solution would be to use the -temp_folder option (and the -log option) instead of only the more specific -ptm_configuration option.)

Best regards,
Harald

**Comment by jflucier** [comment]
the user mods are now detected when I call searchgui pathsettingcli with -ptm_configuration.

tks so much Harald for your precious help.

I am currently runniing a full analysis. Once everything pass I will get back to you.

JF

**Comment by hbarsnes** [comment]
Hi JF,

Great! I will close the issue then. So please open a new one if you come across more issues.

Best regards,
Harald
